### ISSUE TITLE
Download satellite picture by astropy

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/SDSS_satellites#3]
DOD - download features by astropy of 3 satellite galaxies, and a upload the relevant code
to this issue.

***Make sure you take the maximum features possible***

**Comment by noamchouchena** [comment]
#1-Download and open the zip file from astroquery.
# 2-Download image by satellite galaxies coordinates from pandas.
#3-Download their properties according to the appropriate coordinates.
#4- Add all the data you extracted to the pandas table.

**Comment by noamchouchena** [comment]
the last version of the code
![image](https://user-images.githubusercontent.com/55201253/67712269-5539b280-f9cc-11e9-8202-28cedef9b18b.png)

**Comment by noamchouchena** [comment]
גילויים:
איך ניתן להוריד תמונה בעזרת שאילתה באסטרוקוורי דרך קורדינטות ודרך שאילתה של נתונים.
כיצד ניתן בעזרת שימוש בקורדינטות להוציא מידע על גלקסייה.
כיצד ניתן להוריד ספקטרום של גלקסיה ותמונה  שלה דרך קורדינטות.
(ההורדה היא כפיטס פייל לעניין התמונה)
