### ISSUE TITLE
Set Astropy env

### ISSUE THREAD

**Issue by tussbaum** [GalaxyHunters/SDSS_satellites#7]
Set work environment for your pycharm code and ipython. on your computer.

DOD - example code of astropy working

**Comment by noamchouchena** [comment]
[
![p](https://user-images.githubusercontent.com/55201253/64872461-ec7ebc80-d64f-11e9-8a82-2f6b7769aa51.PNG)
](url)

**Comment by tussbaum** [comment]
Looks great, note that you should connect that to your pycharm. (that's the task here)

Go to pycharm preferences and find there the used interpreter, change it to the path of this python you use here in this cmd example.

**Comment by tussbaum** [comment]
2 points for you, do answer me with an additional comment here.
1. Did you use the conda for installing or did you do something else
2. When you finish, move the issue to the next column (In review) which means you have finished this task and go to the satellite SDSS features task

**Comment by noamchouchena** [comment]
![image](https://user-images.githubusercontent.com/55201253/65065101-77322500-d98a-11e9-9b91-49350674d14f.png)

**Comment by noamchouchena** [comment]
for the first time i used regular python without environment for the download
